# Site title
title: Wen Taichi
description: Unity Game Developer

# URL
baseurl: ""
url: ""

# Pagination
paginate: 5
paginate_path: /blog/page:num/
permalink: /blog/:year/:month/:title/

# Social media links in footer
email: daleth90@gmail.com
linkedin: "wentaichi"
github: "daleth90"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# Optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Collection
collections:
  - projects

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
